// vitest skeleton generator: one EARS requirement → one `it(...)` block.
//
// Output shape:
//   describe('<fileName>', () => {
//     describe('<sourceNodeName>', () => {
//       it('<requirement.text>', () => {
//         // arrange: <pattern-specific guidance>
//         // act:     <pattern-specific guidance>
//         // assert:  <pattern-specific guidance>
//         throw new Error('TODO: implement test for R1');
//       });
//     });
//   });
//
// The generated tests are intentionally `throw new Error('TODO')` so they
// FAIL loudly until a human fills them in. This keeps the spec → test
// linkage honest: if a requirement exists, a failing test exists.
//
// The arrange/act/assert comments are tailored to the EARS pattern so the
// human filling them in has a concrete shape to follow, not just three
// empty placeholders. See `patternScaffold` below for the per-pattern
// guidance and ADR-0006 for the rationale.
import type { EarsPattern, EarsRequirement, SpecOutput } from "./llm/index.ts";

export interface GenerateOptions {
  /** Top-level describe label (usually the Figma file name). */
  fileName: string;
}

/** Public API: a complete .test.ts file as a single string. */
export function generateTestFile(
  spec: SpecOutput,
  opts: GenerateOptions,
): string {
  const grouped = groupBySource(spec.requirements);
  const blocks: string[] = [];
  for (const [groupName, reqs] of grouped) {
    const its = reqs.map((r) => renderIt(r)).join("\n\n");
    blocks.push(
      `  describe(${asLiteral(groupName)}, () => {\n${its}\n  });`,
    );
  }
  const header =
    `// AUTOGENERATED by figspec-pilot M5 (test-gen.ts).\n` +
    `// One ` +
    `it()` +
    ` per EARS requirement. Tests throw 'TODO' until filled in.\n` +
    `import { describe, it } from "vitest";\n\n`;
  return (
    header +
    `describe(${asLiteral(opts.fileName)}, () => {\n` +
    blocks.join("\n\n") +
    `\n});\n`
  );
}

/** Group requirements by the first source node's name; fall back to "(no source)". */
export function groupBySource(
  requirements: EarsRequirement[],
): Map<string, EarsRequirement[]> {
  const out = new Map<string, EarsRequirement[]>();
  for (const r of requirements) {
    const key = r.source[0]?.nodeName ?? "(no source)";
    const bucket = out.get(key) ?? [];
    bucket.push(r);
    out.set(key, bucket);
  }
  return out;
}

/** Pattern-specific arrange / act / assert scaffold lines.
 *  Each EARS pattern implies a different test shape; emitting that shape
 *  as a comment removes the "blank canvas" feel of the TODO stub and
 *  tells the human exactly what they need to wire up.
 */
export function patternScaffold(pattern: EarsPattern): string[] {
  switch (pattern) {
    case "ubiquitous":
      return [
        `      // arrange: set the system in its default, always-on state`,
        `      // act:     (no trigger; this is an invariant that must hold continuously)`,
        `      // assert:  verify the property in the "shall" clause`,
      ];
    case "event":
      return [
        `      // arrange: set up the state where the trigger can fire`,
        `      // act:     trigger the event described before "shall"`,
        `      // assert:  verify the post-condition described after "shall"`,
      ];
    case "state":
      return [
        `      // arrange: drive the system into the "While" state`,
        `      // act:     observe behaviour while the state condition holds`,
        `      // assert:  verify the "shall" clause is true throughout the state`,
      ];
    case "optional":
      return [
        `      // arrange: enable the feature / configuration named after "Where"`,
        `      // act:     exercise the system with that feature active`,
        `      // assert:  verify the "shall" clause holds when the feature is on`,
      ];
    case "unwanted":
      return [
        `      // arrange: set up the precondition that allows the unwanted event`,
        `      // act:     trigger the condition described after "If"`,
        `      // assert:  verify the recovery / rejection in the "shall" clause`,
      ];
  }
}

/** Render one `it(...)` block with pattern-aware arrange/act/assert comments. */
export function renderIt(req: EarsRequirement): string {
  const title = `[${req.id}] ${req.text}`;
  const sourceTrail =
    req.source.length > 0
      ? req.source
          .map((s) => `${s.nodeId}/${s.nodeName}`)
          .join(", ")
      : "(no source)";
  return [
    `    it(${asLiteral(title)}, () => {`,
    `      // pattern: ${req.pattern}`,
    `      // source: ${sourceTrail}`,
    ...patternScaffold(req.pattern),
    `      throw new Error(${asLiteral(`TODO: implement test for ${req.id}`)});`,
    `    });`,
  ].join("\n");
}

/** TS string literal with JSON escaping; double quotes to match tsconfig style. */
export function asLiteral(s: string): string {
  return JSON.stringify(s);
}
